//clases básicas
var lord = {
    n: "Lord",
    weapon: "sword",
    promotesTo: ["Great Lord"],
    baseHp: 18,
    baseStr: 6,
    baseMag: 0,
    baseSkl: 5,
    baseLck: 0,
    baseSpd: 7,
    baseDef: 7,
    baseRes: 0,
    baseHpGr: 40,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var tactician = {
    n: "Tactician",
    weapon: ["sword", "tome"],
    promotesTo: ["Grandmaster"],
    baseHp: 16,
    baseStr: 4,
    baseMag: 3,
    baseSkl: 5,
    baseSpd: 5,
    baseLck: 0,
    baseDef: 5,
    baseRes: 3,
    baseHpGr: 40,
    baseStrGr: 15,
    baseMagGr: 15,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 10,
}
var cavalier = {
    n: "Cavalier",
    weapon: ["sword", "lance"],
    promotesTo: ["Paladin", "Great Knight"],
    baseHp: 18,
    baseStr: 6,
    baseMag: 0,
    baseSkl: 5,
    baseSpd: 6,
    baseLck: 0,
    baseDef: 7,
    baseRes: 0,
    baseHpGr: 45,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var thief = {
    n: "Thief",
    weapon: "sword",
    promotesTo: ["Assasin", "Trickster"],
    baseHp: 16,
    baseStr: 3,
    baseMag: 0,
    baseSkl: 6,
    baseSpd: 8,
    baseLck: 0,
    baseDef: 2,
    baseRes: 0,
    baseHpGr: 35,
    baseStrGr: 15,
    baseMagGr: 5,
    baseSklGr: 25,
    baseSpdGr: 25,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 5,
}
var knight = {
    n: "Knight",
    weapon: "lance",
    promotesTo: ["Great Knight", "General"],
    baseHp: 18,
    baseStr: 8,
    baseMag: 0,
    baseSkl: 4,
    baseSpd: 2,
    baseLck: 0,
    baseDef: 11,
    baseRes: 0,
    baseHpGr: 50,
    baseStrGr: 25,
    baseMagGr: 0,
    baseSklGr: 15,
    baseSpdGr: 10,
    baseLckGr: 0,
    baseDefGr: 15,
    baseResGr: 4,
}
var myrmidion = {
    n: "Myrmidion",
    weapon: "sword",
    promotesTo: ["Swordmaster", "Assassin"],
    baseHp: 16,
    baseStr: 4,
    baseMag: 1,
    baseSkl: 9,
    baseSpd: 10,
    baseLck: 0,
    baseDef: 4,
    baseRes: 1,
    baseHpGr: 40,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 25,
    baseSpdGr: 25,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 5,
}
var mercenary = {
    n: "Mercenary",
    weapon: "sword",
    promotesTo: ["Hero", "Bow Knight"],
    baseHp: 18,
    baseStr: 5,
    baseMag: 0,
    baseSkl: 8,
    baseSpd: 7,
    baseLck: 0,
    baseDef: 5,
    baseRes: 0,
    baseHpGr: 45,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 25,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var fighter = {
    n: "Fighter",
    weapon: "axe",
    promotesTo: ["Warrior", "Hero"],
    baseHp: 20,
    baseStr: 8,
    baseMag: 0,
    baseSkl: 5,
    baseSpd: 5,
    baseLck: 0,
    baseDef: 4,
    baseRes: 0,
    baseHpGr: 45,
    baseStrGr: 25,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var barbarian = {
    n: "Barbarian",
    weapon: "axe",
    promotesTo: ["Berserker", "Warrior"],
    baseHp: 22,
    baseStr: 8,
    baseMag: 0,
    baseSkl: 3,
    baseSpd: 8,
    baseLck: 0,
    baseDef: 3,
    baseRes: 0,
    baseHpGr: 50,
    baseStrGr: 25,
    baseMagGr: 0,
    baseSklGr: 15,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 5,
}
var archer = {
    n: "Archer",
    weapon: "bow",
    promotesTo: ["Bow Knight", "Sniper"],
    baseHp: 16,
    baseStr: 5,
    baseMag: 0,
    baseSkl: 8,
    baseSpd: 6,
    baseLck: 0,
    baseDef: 5,
    baseRes: 0,
    baseHpGr: 45,
    baseStrGr: 15,
    baseMagGr: 0,
    baseSklGr: 30,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var pegasusKnight = {
    n: "Pegasus Knight",
    weapon: "lance",
    promotesTo: ["Falcon Knight", "Dark Flier"],
    baseHp: 16,
    baseStr: 4,
    baseMag: 2,
    baseSkl: 7,
    baseSpd: 8,
    baseLck: 0,
    baseDef: 4,
    baseRes: 6,
    baseHpGr: 40,
    baseStrGr: 15,
    baseMagGr: 5,
    baseSklGr: 25,
    baseSpdGr: 25,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 10,
}
var wyvernRider = {
    n: "Wyvern Rider",
    weapon: "axe",
    promotesTo: ["Wyvern Lord", "Griffon Rider"],
    baseHp: 19,
    baseStr: 7,
    baseMag: 0,
    baseSkl: 6,
    baseSpd: 5,
    baseLck: 0,
    baseDef: 8,
    baseRes: 0,
    baseHpGr: 45,
    baseStrGr: 30,
    baseMagGr: 0,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var mage = {
    n: "Mage",
    weapon: "tome",
    promotesTo: ["Dark Knight", "Sage"],
    baseHp: 16,
    baseStr: 0,
    baseMag: 4,
    baseSkl: 3,
    baseSpd: 4,
    baseLck: 0,
    baseDef: 2,
    baseRes: 3,
    baseHpGr: 35,
    baseStrGr: 0,
    baseMagGr: 20,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 10,
}
var darkMage = {
    n: "Dark Mage",
    weapon: "tome",
    promotesTo: ["Sorcerer", "Dark Knight"],
    baseHp: 18,
    baseStr: 1,
    baseMag: 3,
    baseSkl: 2,
    baseSpd: 3,
    baseLck: 0,
    baseDef: 4,
    baseRes: 4,
    baseHpGr: 50,
    baseStrGr: 5,
    baseMagGr: 15,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 10,
}

var priest = {
    n: "Priest",
    weapon: "staff",
    promotesTo: ["Sage", "War Monk"],
    baseHp: 16,
    baseStr: 0,
    baseMag: 3,
    baseSkl: 2,
    baseSpd: 4,
    baseLck: 0,
    baseDef: 1,
    baseRes: 6,
    baseHpGr: 35,
    baseStrGr: 5,
    baseMagGr: 15,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 15,
}
var cleric = {
    n: "Cleric",
    weapon: "staff",
    promotesTo: ["Sage", "War Cleric"],
    baseHp: 16,
    baseStr: 0,
    baseMag: 3,
    baseSkl: 2,
    baseSpd: 4,
    baseLck: 0,
    baseDef: 1,
    baseRes: 6,
    baseHpGr: 35,
    baseStrGr: 5,
    baseMagGr: 15,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 15,
}
var troubadour = {
    n: "Troubadour",
    weapon: "staff",
    promotesTo: ["War Cleric", "Valkyrie"],
    baseHp: 16,
    baseStr: 0,
    baseMag: 3,
    baseSkl: 2,
    baseSpd: 5,
    baseLck: 0,
    baseDef: 1,
    baseRes: 5,
    baseHpGr: 35,
    baseStrGr: 0,
    baseMagGr: 20,
    baseSklGr: 10,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 15,
}
//clases avanzadas
var greatLord = {
    n: "Great Lord",
    weapon: ["sword", "lance"],
    baseHp: 23,
    baseStr: 10,
    baseMag: 0,
    baseSkl: 7,
    baseSpd: 9,
    baseLck: 0,
    baseDef: 10,
    baseRes: 3,
    baseHpGr: 40,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var grandmaster = {
    n: "Grandmaster",
    weapon: ["sword", "tome"],
    baseHp: 20,
    baseStr: 7,
    baseMag: 6,
    baseSkl: 7,
    baseSpd: 7,
    baseLck: 0,
    baseDef: 7,
    baseRes: 5,
    baseHpGr: 40,
    baseStrGr: 15,
    baseMagGr: 15,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 10,
}
var paladin = {
    n: "Paladin",
    weapon: ["sword", "lance"],
    baseHp: 25,
    baseStr: 9,
    baseMag: 1,
    baseSkl: 7,
    baseSpd: 8,
    baseLck: 0,
    baseDef: 10,
    baseRes: 6,
    baseHpGr: 45,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 10,
}
var greatKnight = {
    n: "Great Knight",
    weapon: ["sword", "lance", "axe"],
    baseHp: 26,
    baseStr: 11,
    baseMag: 0,
    baseSkl: 6,
    baseSpd: 5,
    baseLck: 0,
    baseDef: 14,
    baseRes: 1,
    baseHpGr: 50,
    baseStrGr: 25,
    baseMagGr: 0,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 15,
    baseResGr: 5,
}
var general = {
    n: "General",
    weapon: ["lance", "axe"],
    baseHp: 28,
    baseStr: 8,
    baseMag: 0,
    baseSkl: 4,
    baseSpd: 2,
    baseLck: 0,
    baseDef: 11,
    baseRes: 0,
    baseHpGr: 50,
    baseStrGr: 25,
    baseMagGr: 0,
    baseSklGr: 15,
    baseSpdGr: 10,
    baseLckGr: 0,
    baseDefGr: 15,
    baseResGr: 10,
}
var swordmaster = {
    n: "Swordmaster",
    weapon: "sword",
    baseHp: 20,
    baseStr: 7,
    baseMag: 2,
    baseSkl: 11,
    baseSpd: 13,
    baseLck: 0,
    baseDef: 6,
    baseRes: 4,
    baseHpGr: 40,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 25,
    baseSpdGr: 25,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 10,
}
var hero = {
    n: "Hero",
    weapon: ["sword", "axe"],
    baseHp: 22,
    baseStr: 8,
    baseMag: 1,
    baseSkl: 11,
    baseSpd: 10,
    baseLck: 0,
    baseDef: 8,
    baseRes: 3,
    baseHpGr: 45,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 25,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var warrior = {
    n: "Warrior",
    weapon: ["axe", "bow"],
    baseHp: 28,
    baseStr: 12,
    baseMag: 0,
    baseSkl: 8,
    baseSpd: 7,
    baseLck: 0,
    baseDef: 7,
    baseRes: 3,
    baseHpGr: 45,
    baseStrGr: 25,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var berserker = {
    n: "Berserker",
    weapon: "axe",
    baseHp: 30,
    baseStr: 13,
    baseMag: 0,
    baseSkl: 5,
    baseSpd: 11,
    baseLck: 0,
    baseDef: 5,
    baseRes: 6,
    baseHpGr: 50,
    baseStrGr: 25,
    baseMagGr: 0,
    baseSklGr: 15,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 5,
}
var sniper = {
    n: "Sniper",
    weapon: "bow",
    baseHp: 20,
    baseStr: 7,
    baseMag: 1,
    baseSkl: 12,
    baseSpd: 9,
    baseLck: 0,
    baseDef: 10,
    baseRes: 3,
    baseHpGr: 45,
    baseStrGr: 15,
    baseMagGr: 0,
    baseSklGr: 30,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 15,
    baseResGr: 5,
}
var bowKnight = {
    n: "Bow Knight",
    weapon: ["sword", "bow"],
    baseHp: 24,
    baseStr: 8,
    baseMag: 0,
    baseSkl: 10,
    baseSpd: 10,
    baseLck: 0,
    baseDef: 6,
    baseRes: 2,
    baseHpGr: 50,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 25,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 5,
}
var assassin = {
    n: "Assassin",
    weapon: ["sword", "bow"],
    baseHp: 21,
    baseStr: 8,
    baseMag: 0,
    baseSkl: 13,
    baseSpd: 12,
    baseLck: 0,
    baseDef: 5,
    baseRes: 1,
    baseHpGr: 40,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 30,
    baseSpdGr: 25,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 5,
}
var trickster = {
    n: "Trickster",
    weapon: ["sword", "staff"],
    baseHp: 19,
    baseStr: 4,
    baseMag: 4,
    baseSkl: 10,
    baseSpd: 11,
    baseLck: 0,
    baseDef: 3,
    baseRes: 5,
    baseHpGr: 35,
    baseStrGr: 10,
    baseMagGr: 15,
    baseSklGr: 25,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 10,
}
var darkFlier = {
    n: "Dark Flier",
    weapon: ["lance", "tome"],
    baseHp: 19,
    baseStr: 5,
    baseMag: 6,
    baseSkl: 8,
    baseSpd: 10,
    baseLck: 0,
    baseDef: 6,
    baseRes: 9,
    baseHpGr: 40,
    baseStrGr: 10,
    baseMagGr: 15,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 10,
}
var sorcerer = {
    n: "Sorcerer",
    weapon: "tome",
    baseHp: 23,
    baseStr: 2,
    baseMag: 6,
    baseSkl: 4,
    baseSpd: 4,
    baseLck: 0,
    baseDef: 7,
    baseRes: 7,
    baseHpGr: 45,
    baseStrGr: 0,
    baseMagGr: 20,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 10,
}
var falconKnight = {
    n: "FalconKnight",
    weapon: ["lance", "staff"],
    baseHp: 20,
    baseStr: 6,
    baseMag: 3,
    baseSkl: 10,
    baseSpd: 11,
    baseLck: 0,
    baseDef: 6,
    baseRes: 9,
    baseHpGr: 40,
    baseStrGr: 15,
    baseMagGr: 10,
    baseSklGr: 25,
    baseSpdGr: 25,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 10,
}
var wyvernLord = {
    n: "Wyvern Lord",
    weapon: ["axe", "lance"],
    baseHp: 24,
    baseStr: 11,
    baseMag: 0,
    baseSkl: 8,
    baseSpd: 7,
    baseLck: 0,
    baseDef: 11,
    baseRes: 3,
    baseHpGr: 45,
    baseStrGr: 30,
    baseMagGr: 0,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var griffonRider = {
    n: "Griffon Rider",
    weapon: "axe",
    baseHp: 22,
    baseStr: 9,
    baseMag: 0,
    baseSkl: 10,
    baseSpd: 9,
    baseLck: 0,
    baseDef: 8,
    baseRes: 3,
    baseHpGr: 45,
    baseStrGr: 25,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 5,
}
var sage = {
    n: "Sage",
    weapon: ["tome", "staff"],
    baseHp: 20,
    baseStr: 1,
    baseMag: 7,
    baseSkl: 5,
    baseSpd: 7,
    baseLck: 0,
    baseDef: 4,
    baseRes: 5,
    baseHpGr: 35,
    baseStrGr: 0,
    baseMagGr: 20,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 10,
}
var darkKnight = {
    n: "Dark Knight",
    weapon: ["sword", "tome"],
    baseHp: 25,
    baseStr: 4,
    baseMag: 5,
    baseSkl: 6,
    baseSpd: 5,
    baseLck: 0,
    baseDef: 9,
    baseRes: 5,
    baseHpGr: 50,
    baseStrGr: 15,
    baseMagGr: 15,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var warMonk = {
    n: "War Monk",
    weapon: ["staff", "axe"],
    baseHp: 24,
    baseStr: 5,
    baseMag: 5,
    baseSkl: 4,
    baseSpd: 6,
    baseLck: 0,
    baseDef: 6,
    baseRes: 6,
    baseHpGr: 35,
    baseStrGr: 5,
    baseMagGr: 15,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 15,
}
var warCleric = {
    n: "War Cleric",
    weapon: ["staff", "axe"],
    baseHp: 24,
    baseStr: 5,
    baseMag: 5,
    baseSkl: 4,
    baseSpd: 6,
    baseLck: 0,
    baseDef: 6,
    baseRes: 6,
    baseHpGr: 35,
    baseStrGr: 5,
    baseMagGr: 15,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 15,
}
var valkyrie = {
    n: "Valkyrie",
    weapon: ["tome", "staff"],
    baseHp: 19,
    baseStr: 0,
    baseMag: 5,
    baseSkl: 4,
    baseSpd: 8,
    baseLck: 0,
    baseDef: 3,
    baseRes: 8,
    baseHpGr: 35,
    baseStrGr: 0,
    baseMagGr: 20,
    baseSklGr: 10,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 15,
}
//clases especiales 
var bride = {
    n: "Bride",
    weapon: ["lance", "bow", "staff"],
    baseHp: 21,
    baseStr: 7,
    baseMag: 6,
    baseSkl: 11,
    baseSpd: 10,
    baseLck: 0,
    baseDef: 7,
    baseRes: 6,
    baseHpGr: 40,
    baseStrGr: 20,
    baseMagGr: 10,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 10,
}
var villager = {
    n: "Villager",
    weapon: "lance",
    promotesTo: [],
    baseHp: 16,
    baseStr: 1,
    baseMag: 0,
    baseSkl: 1,
    baseSpd: 1,
    baseLck: 0,
    baseDef: 1,
    baseRes: 0,
    baseHpGr: 35,
    baseStrGr: 10,
    baseMagGr: 0,
    baseSklGr: 5,
    baseSpdGr: 5,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var dancer = {
    n: "Dancer",
    weapon: "sword",
    promotesTo: [],
    baseHp: 16,
    baseStr: 1,
    baseMag: 1,
    baseSkl: 5,
    baseSpd: 8,
    baseLck: 0,
    baseDef: 3,
    baseRes: 1,
    baseHpGr: 35,
    baseStrGr: 5,
    baseMagGr: 0,
    baseSklGr: 25,
    baseSpdGr: 25,
    baseLckGr: 0,
    baseDefGr: 5,
    baseResGr: 5,
}
var taguelM = {
    n: "Taguel M",
    weapon: "stone",
    promotesTo: [],
    baseHp: 18,
    baseStr: 2,
    baseMag: 0,
    baseSkl: 4,
    baseSpd: 5,
    baseLck: 0,
    baseDef: 3,
    baseRes: 2,
    baseHpGr: 45,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 15,
    baseSpdGr: 15,
    baseLckGr: 0,
    baseDefGr: 15,
    baseResGr: 5,
}
var taguelF = {
    n: "Taguel F",
    weapon: "stone",
    promotesTo: [],
    baseHp: 18,
    baseStr: 2,
    baseMag: 0,
    baseSkl: 4,
    baseSpd: 5,
    baseLck: 0,
    baseDef: 3,
    baseRes: 2,
    baseHpGr: 40,
    baseStrGr: 15,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 4,
}
var manakete = {
    n: "Manakete",
    weapon: "stone",
    promotesTo: [],
    baseHp: 18,
    baseStr: 2,
    baseMag: 0,
    baseSkl: 1,
    baseSpd: 1,
    baseLck: 0,
    baseDef: 2,
    baseRes: 2,
    baseHpGr: 50,
    baseStrGr: 20,
    baseMagGr: 5,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 15,
    baseResGr: 15,
}
var lodestar = {
    n: "Lodestar",
    weapon: "sword",
    baseHp: 21,
    baseStr: 9,
    baseMag: 1,
    baseSkl: 10,
    baseSpd: 10,
    baseLck: 0,
    baseDef: 8,
    baseRes: 4,
    baseHpGr: 40,
    baseStrGr: 20,
    baseMagGr: 0,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 5,
}
var dreadFighter = {
    n: "Dread Fighter",
    weapon: ["sword", "axe", "tome"],
    baseHp: 22,
    baseStr: 8,
    baseMag: 4,
    baseSkl: 7,
    baseSpd: 9,
    baseLck: 0,
    baseDef: 7,
    baseRes: 10,
    baseHpGr: 40,
    baseStrGr: 20,
    baseMagGr: 10,
    baseSklGr: 20,
    baseSpdGr: 20,
    baseLckGr: 0,
    baseDefGr: 10,
    baseResGr: 10,
}
var noClass = {
    n: "-",
    weapon: [],
    promotesTo: [],
    baseHp: 0,
    baseStr: 0,
    baseMag: 0,
    baseSkl: 0,
    baseSpd: 0,
    baseLck: 0,
    baseDef: 0,
    baseRes: 0,
    baseHpGr: 0,
    baseStrGr: 0,
    baseMagGr: 0,
    baseSklGr: 0,
    baseSpdGr: 0,
    baseLckGr: 0,
    baseDefGr: 0,
    baseResGr: 0,
}

//

var nopromotesTo = [lord, tactician, cavalier, knight, myrmidion, mercenary, fighter, barbarian, archer, thief, pegasusKnight, wyvernRider, mage, darkMage, priest, cleric, troubadour, villager, dancer, taguelF, taguelM, manakete, bride, dreadFighter];
var allClasses = [lord, greatLord, tactician, grandmaster, cavalier, paladin, greatKnight, knight, general, myrmidion, swordmaster, mercenary, hero, fighter, warrior, barbarian, berserker, archer, sniper, bowKnight, thief, assassin, trickster, pegasusKnight, falconKnight, darkFlier, wyvernRider, wyvernLord, griffonRider, mage, darkMage, sage, sorcerer, darkKnight, priest, cleric, warCleric, warMonk, troubadour, valkyrie, villager, dancer, taguelF, taguelM, manakete, bride, dreadFighter];
var allRobinCl = [tactician, grandmaster, cavalier, paladin, greatKnight, knight, general, myrmidion, swordmaster, mercenary, hero, archer, sniper, bowKnight, thief, assassin, trickster, pegasusKnight, falconKnight, darkFlier, wyvernRider, wyvernLord, griffonRider, mage, darkMage, sage, sorcerer, darkKnight, cleric, warCleric, troubadour, valkyrie, bride];
var onlyClF = [cleric, warCleric, troubadour, valkyrie, bride];
var onlyClM = [fighter, barbarian, warrior, berserker, dreadFighter];


function getBaseArr(cl){
    return [ cl.baseHp, cl.baseStr, cl.baseMag, cl.baseSkl, cl.baseSpd, cl.baseLck, cl.baseDef, cl.baseRes];
}
function getGrArrC(cl){
    return [cl.baseHpGr, cl.baseStrGr, cl.baseMagGr, cl.baseSklGr, cl.baseSpdGr, cl.baseLckGr, cl.baseDefGr, cl.baseResGr];
}