var robin = {
    n: "Robin",
    vName: "robin",
    claseBase: ["Tactician"],
    sRank: ["Chrom", "Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Lissa", "Sully", "Miriel", "Sumia", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche", "Anna"],
    isChilde: false,
    gender: "F",
    baseHp: 3,
    baseStr: 2,
    baseMag: 2,
    baseSkl: 0,
    baseSpd: 1,
    baseLck: 4,
    baseDef: 1,
    baseRes: 1,
    hpMod: 19,
    strMod: 6,
    magMod: 5,
    sklMod: 5,
    spdMod: 6,
    lckMod: 4,
    defMod: 6,
    resMod: 4,
    baseHpGr: 40,
    baseStrGr: 40,
    baseMagGr: 35,
    baseSklGr: 35,
    baseSpdGr: 35,
    baseLckGr: 55,
    baseDefGr: 30,
    baseResGr: 20,
    hpGr: 40,
    strGr: 40,
    magGr: 35,
    sklGr: 35,
    spdGr: 35,
    lckGr: 55,
    defGr: 30,
    resGr: 20,
}

var chrom = {
    n: "Chrom",
    vName: "chrom",
    claseBase: ["Lord", "Cavalier", "Archer"],
    sRank: ["Robin", "Sumia", "Maribelle", "Sully", "Olivia"],
    aRank: ["Vaike", "Gaius", "Lissa", "Frederick"],
    isChilde: false,
    gender: "M",
    baseHp: 2,
    baseStr: 1,
    baseMag: 1,
    baseSkl: 3,
    baseSpd: 1,
    baseLck: 5,
    baseDef: 0,
    baseRes: 1,
    hpMod: 20,
    strMod: 7,
    magMod: 1,
    sklMod: 8,
    spdMod: 8,
    lckMod: 5,
    defMod: 7,
    resMod: 1,
    baseHpGr: 45,
    baseStrGr: 40,
    baseMagGr: 10,
    baseSklGr: 40,
    baseSpdGr: 40,
    baseLckGr: 70,
    baseDefGr: 35,
    baseResGr: 20,
    hpGr: 45,
    strGr: 40,
    magGr: 19,
    sklGr: 40,
    spdGr: 40,
    lckGr: 70,
    defGr: 35,
    resGr: 20,
}
var lissa = {
    n: "Lissa",
    vName: "lissa",
    claseBase: ["Cleric", "Pegasus Knight", "Troubadour"],
    sRank: ["Virion", "Frederick", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Henry", "Donnel"],
    aRank: ["Robin", "Chrom", "Maribelle"],
    isChilde: false,
    gender: "F",
    baseHp: 1,
    baseStr: 1,
    baseMag: 2,
    baseSkl: 2,
    baseSpd: 0,
    baseLck: 8,
    baseDef: 2,
    baseRes: -2,
    hpMod: 17,
    strMod: 1,
    magMod: 5,
    sklMod: 4,
    spdMod: 4,
    lckMod: 8,
    defMod: 3,
    resMod: 4,
    baseHpGr: 35,
    baseStrGr: 25,
    baseMagGr: 35,
    baseSklGr: 30,
    baseSpdGr: 35,
    baseLckGr: 65,
    baseDefGr: 15,
    baseResGr: 35,
    hpGr: 35,
    strGr: 25,
    magGr: 35,
    sklGr: 30,
    spdGr: 35,
    lckGr: 65,
    defGr: 15,
    resGr: 35,
}
var frederick = {
    n: "Frederick",
    vName: "frederick",
    claseBase: ["Cavalier", "Knight", "Wyvern Rider"],   
    sRank: ["Cordelia", "Sumia", "Robin", "Lissa", "Sully", "Miriel", "Marielle", "Panne", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Chrom", "Virion", "Henry"],
    isChilde: false,
    gender: "M",
    baseHp: 10,
    baseStr: 7,
    baseMag: 2,
    baseSkl: 7,
    baseSpd: 4,
    baseLck: 6,
    baseDef: 7,
    baseRes: 3,
    hpMod: 28,
    strMod: 13,
    magMod: 2,
    sklMod: 12,
    spdMod: 10,
    lckMod: 6,
    defMod: 14,
    resMod: 3,
    baseHpGr: 60,
    baseStrGr: 40,
    baseMagGr: 10,
    baseSklGr: 40,
    baseSpdGr: 35,
    baseLckGr: 40,
    baseDefGr: 40,
    baseResGr: 20,
    hpGr: 60,
    strGr: 40,
    magGr: 10,
    sklGr: 40,
    spdGr: 35,
    lckGr: 40,
    defGr: 40,
    resGr: 20,
}
var sully = {
    n: "Sully",
    vName: "sully",
    claseBase: ["Cavalier", "Myrmidion", "Wyvern Rider"],
    sRank: ["Gaius", "Donnel", "Chrom", "Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Miriel", "Sumia"],
    isChilde: false,
    gender: "F",
    baseHp: 2,
    baseStr: 1,
    baseMag: 1,
    baseSkl: 3,
    baseSpd: 2,
    baseLck: 6,
    baseDef: 0,
    baseRes: 2,
    hpMod: 20,
    strMod: 7,
    magMod: 1,
    sklMod: 8,
    spdMod: 8,
    lckMod: 6,
    defMod: 7,
    resMod: 2,
    baseHpGr: 40,
    baseStrGr: 35,
    baseMagGr: 20,
    baseSklGr: 40,
    baseSpdGr: 40,
    baseLckGr: 60,
    baseDefGr: 35,
    baseResGr: 20,
    hpGr: 40,
    strGr: 35,
    magGr: 20,
    sklGr: 40,
    spdGr: 40,
    lckGr: 60,
    defGr: 35,
    resGr: 20,
}

//solo tiene baseGR
var virion = {
    n: "Virion",
    vName: "virion",
    claseBase: ["Archer", "Wyvern Rider", "Mage"],
    sRank: ["Tharja", "Lissa", "Panne", "Cordelia", "Robin", "Sully", "Miriel", "Maribelle", "Nowi", "Olivia", "Cherche"],
    aRank: ["Frederick", "Libra"],
    isChilde: false,
    gender: "M",
    baseHp: 3,
    baseStr: 1,
    baseMag: 0,
    baseSkl: 1,
    baseSpd: -1,
    baseLck: 7,
    baseDef: 1,
    baseRes: 1,
    hpMod: 19,
    strMod: 6,
    magMod: 0,
    sklMod: 9,
    spdMod: 5,
    lckMod: 7,
    defMod: 6,
    resMod: 1,
    baseHpGr: 35,
    baseStrGr: 40,
    baseMagGr: 30,
    baseSklGr: 40,
    baseSpdGr: 45,
    baseLckGr: 40,
    baseDefGr: 25,
    baseResGr: 25,
}
var stahl = {
    n: "Stahl",
    vName: "stahl",
    claseBase: ["Cavalier", "Archer", "Myrmidion"],
    sRank: ["Robin", "Cordelia", "Lissa", "Sully", "Miriel", "Maribelle", "Panne", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Kellam", "Donnel"],
    isChilde: false,
    gender: "M",
    baseHp: 4,
    baseStr: 2,
    baseMag: 0,
    baseSkl: 2,
    baseSpd: 0,
    baseLck: 5,
    baseDef: 1,
    baseRes: 1,
    hpMod: 22,
    strMod: 8,
    magMod: 0,
    sklMod: 7,
    spdMod: 6,
    lckMod: 5,
    defMod: 8,
    resMod: 1,
    baseHpGr: 50,
    baseStrGr: 45,
    baseMagGr: 10,
    baseSklGr: 35,
    baseSpdGr: 30,
    baseLckGr: 50,
    baseDefGr: 50,
    baseResGr: 10,
}
var vaike = {
    n: "Vaike",
    vName: "vaike",
    claseBase: ["Barbarian", "Fighter", "Thief"],
    sRank: ["Robin", "Maribelle", "Olivia", "Lissa", "Miriel", "Sully", "Panne", "Cordelia", "Nowi", "Tharja", "Cherche"],
    aRank: ["Chrom", "Lon'qu"],
    isChilde: false,
    gender: "M",
    baseHp: 2,
    baseStr: 1,
    baseMag: 0,
    baseSkl: 5,
    baseSpd: -2,
    baseLck: 4,
    baseDef: 2,
    baseRes: 0,
    hpMod: 24,
    strMod: 9,
    magMod: 0,
    sklMod: 8,
    spdMod: 6,
    lckMod: 4,
    defMod: 5,
    resMod: 0,
    baseHpGr: 60,
    baseStrGr: 50,
    baseMagGr: 10,
    baseSklGr: 45,
    baseSpdGr: 35,
    baseLckGr: 45,
    baseDefGr: 40,
    baseResGr: 5,
}
var miriel = {
    n: "Miriel",
    vName: "miriel",
    claseBase: ["Mage", "Dark Mage", "Troubadour"],
    sRank: ["Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Sully", "Cherche"],
    isChilde: false,
    gender: "F",
    baseHp: 2,
    baseStr: 0,
    baseMag: 2,
    baseSkl: 2,
    baseSpd: 3,
    baseLck: 6,
    baseDef: 1,
    baseRes: 1,
    hpMod: 18,
    strMod: 0,
    magMod: 6,
    sklMod: 5,
    spdMod: 7,
    lckMod: 6,
    defMod: 3,
    resMod: 2,
    baseHpGr: 35,
    baseStrGr: 14,
    baseMagGr: 40,
    baseSklGr: 40,
    baseSpdGr: 40,
    baseLckGr: 50,
    baseDefGr: 20,
    baseResGr: 30,
}
var sumia = {
    n: "Sumia",
    vName: "sumia",
    claseBase: ["Pegasus Knight", "Knight", "Cleric"],
    sRank: ["Chrom", "Frederick", "Gaius", "Henry"],
    aRank: ["Robin", "Cordelia", "Sully"],
    isChilde: false,
    gender: "F",
    baseHp: 2,
    baseStr: 2,
    baseMag: 1,
    baseSkl: 1,
    baseSpd: 4,
    baseLck: 8,
    baseDef: 1,
    baseRes: 1,
    hpMod: 18,
    strMod: 6,
    magMod: 3,
    sklMod: 11,
    spdMod: 11,
    lckMod: 8,
    defMod: 5,
    resMod: 7,
    baseHpGr: 35,
    baseStrGr: 30,
    baseMagGr: 20,
    baseSklGr: 45,
    baseSpdGr: 45,
    baseLckGr: 60,
    baseDefGr: 25,
    baseResGr: 30,
}
var kellam = {
    n: "Kellam",
    vName: "kellam",
    claseBase: ["Knight", "Thief", "Priest"],
    sRank: ["Robin", "Lissa", "Sully", "Miriel", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Stahl", "Donnel"],
    isChilde: false,
    gender: "M",
    baseHp: 3,
    baseStr: 2,
    baseMag: 0,
    baseSkl: 3,
    baseSpd: 3,
    baseLck: 3,
    baseDef: 1,
    baseRes: 2,
    hpMod: 21,
    strMod: 10,
    magMod: 0,
    sklMod: 7,
    spdMod: 5,
    lckMod: 3,
    defMod: 12,
    resMod: 2,
    baseHpGr: 50,
    baseStrGr: 40,
    baseMagGr: 15,
    baseSklGr: 40,
    baseSpdGr: 35,
    baseLckGr: 35,
    baseDefGr: 55,
    baseResGr: 30,
}
var lonqu = {
    n: "Lonqu",
    vName: "lonqu",
    claseBase: ["Myrmidion", "Thief", "Wyvern Rider"],
    sRank: ["Robin", "Lissa", "Sully", "Miriel", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Vaike", "Gregor"],
    isChilde: false,
    gender: "M",
    baseHp: 4,
    baseStr: 2,
    baseMag: 0,
    baseSkl: 2,
    baseSpd: 3,
    baseLck: 7,
    baseDef: 3,
    baseRes: 1,
    hpMod: 20,
    strMod: 6,
    magMod: 1,
    sklMod: 12,
    spdMod: 13,
    lckMod: 7,
    defMod: 7,
    resMod: 2,
    baseHpGr: 40,
    baseStrGr: 35,
    baseMagGr: 20,
    baseSklGr: 50,
    baseSpdGr: 50,
    baseLckGr: 55,
    baseDefGr: 25,
    baseResGr: 20,
}
var donnel = {
    n: "Donnel",
    vName: "donnel",
    claseBase: ["Villager","Fighter", "Mercenary"],
    sRank: ["Robin", "Lissa", "Sully", "Miriel", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Kellam", "Stahl"],
    isChilde: false,
    gender: "M",
    baseHp: 0,
    baseStr: 3,
    baseMag: 0,
    baseSkl: 1,
    baseSpd: 2,
    baseLck: 11,
    baseDef: 2,
    baseRes: 0,
    hpMod: 16,
    strMod: 4,
    magMod: 0,
    sklMod: 2,
    spdMod: 3,
    lckMod: 11,
    defMod: 3,
    resMod: 0,
    baseHpGr: 50,
    baseStrGr: 45,
    baseMagGr: 15,
    baseSklGr: 40,
    baseSpdGr: 45,
    baseLckGr: 80,
    baseDefGr: 35,
    baseResGr: 15,
}
var ricken = {
    n: "Ricken",
    vName: "ricken",
    claseBase: ["Mage", "Cavalier", "Archer"],
    sRank: ["Robin", "Lissa", "Sully", "Miriel", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Gregor", "Henry"],
    isChilde: false,
    gender: "M",
    baseHp: 4,
    baseStr: 3,
    baseMag: 4,
    baseSkl: 3,
    baseSpd: 1,
    baseLck: 10,
    baseDef: 4,
    baseRes: 0,
    hpMod: 20,
    strMod: 3,
    magMod: 8,
    sklMod: 6,
    spdMod: 5,
    lckMod: 10,
    defMod: 6,
    resMod: 3,
    baseHpGr: 50,
    baseStrGr: 45,
    baseMagGr: 15,
    baseSklGr: 40,
    baseSpdGr: 45,
    baseLckGr: 80,
    baseDefGr: 35,
    baseResGr: 15,
}
var maribelle = {
    n: "Maribelle",
    vName: "maribelle",
    claseBase: ["Troubadour", "Pegasus Knight", "Mage"],
    sRank: ["Chrom", "Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Lissa", "Olivia"],
    isChilde: false,
    gender: "F",
    baseHp: 2,
    baseStr: 0,
    baseMag: 2,
    baseSkl: 2,
    baseSpd: 1,
    baseLck: 5,
    baseDef: 2,
    baseRes: 1,
    hpMod: 18,
    strMod: 0,
    magMod: 5,
    sklMod: 4,
    spdMod: 6,
    lckMod: 5,
    defMod: 3,
    resMod: 6,
    baseHpGr: 30,
    baseStrGr: 20,
    baseMagGr: 40,
    baseSklGr: 40,
    baseSpdGr: 30,
    baseLckGr: 80,
    baseDefGr: 10,
    baseResGr: 40,
}
var panne = {
    n: "Panne",
    vName: "panne",
    claseBase: ["Taguel F", "Thief", "Wyvern Rider"],
    sRank: ["Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Cordelia", "Olivia"],
    isChilde: false,
    gender: "F",
    baseHp: 10,
    baseStr: 6,
    baseMag: 1,
    baseSkl: 5,
    baseSpd: 5,
    baseLck: 8,
    baseDef: 4,
    baseRes: 1,
    hpMod: 28,
    strMod: 8,
    magMod: 1,
    sklMod: 9,
    spdMod: 10,
    lckMod: 8,
    defMod: 7,
    resMod: 2,
    baseHpGr: 60,
    baseStrGr: 45,
    baseMagGr: 15,
    baseSklGr: 50,
    baseSpdGr: 55,
    baseLckGr: 40,
    baseDefGr: 40,
    baseResGr: 15,
}
var gaius = {
    n: "Gaius",
    vName: "gaius",
    claseBase: ["Thief", "Myrmidion", "Fighter"],
    sRank: ["Robin", "Lissa", "Sully", "Miriel", "Sumia", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Chrom", "Libra"],
    isChilde: false,
    gender: "M",
    baseHp: 6,
    baseStr: 4,
    baseMag: 0,
    baseSkl: 7,
    baseSpd: 7,
    baseLck: 6,
    baseDef: 3,
    baseRes: 2,
    hpMod: 22,
    strMod: 7,
    magMod: 0,
    sklMod: 13,
    spdMod: 15,
    lckMod: 6,
    defMod: 5,
    resMod: 2,
    baseHpGr: 50,
    baseStrGr: 45,
    baseMagGr: 15,
    baseSklGr: 45,
    baseSpdGr: 45,
    baseLckGr: 35,
    baseDefGr: 25,
    baseResGr: 15,
}
var cordelia = {
    n: "Cordelia",
    vName: "cordelia",
    claseBase: ["Pegasus Knight", "Mercenary", "Dark Mage"],
    sRank: ["Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Sumia", "Panne"],
    isChilde: false,
    gender: "F",
    baseHp: 9,
    baseStr: 5,
    baseMag: 1,
    baseSkl: 6,
    baseSpd: 4,
    baseLck: 9,
    baseDef: 4,
    baseRes: 2,
    hpMod: 25,
    strMod: 9,
    magMod: 3,
    sklMod: 13,
    spdMod: 12,
    lckMod: 8,
    defMod: 8,
    resMod: 8,
    baseHpGr: 50,
    baseStrGr: 45,
    baseMagGr: 15,
    baseSklGr: 35,
    baseSpdGr: 35,
    baseLckGr: 45,
    baseDefGr: 40,
    baseResGr: 25,
}
var gregor = {
    n: "Gregor",
    vName: "gregor",
    claseBase: ["Mercenary", "Barbarian", "Myrmidion"],
    sRank: ["Robin", "Lissa", "Sully", "Miriel", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Lon'qu", "Ricken"],
    isChilde: false,
    gender: "M",
    baseHp: 12,
    baseStr: 7,
    baseMag: 0,
    baseSkl: 5,
    baseSpd: 4,
    baseLck: 8,
    baseDef: 5,
    baseRes: 2,
    hpMod: 30,
    strMod: 12,
    magMod: 0,
    sklMod: 13,
    spdMod: 11,
    lckMod: 8,
    defMod: 10,
    resMod: 2,
    baseHpGr: 60,
    baseStrGr: 40,
    baseMagGr: 10,
    baseSklGr: 40,
    baseSpdGr: 30,
    baseLckGr: 45,
    baseDefGr: 40,
    baseResGr: 10,
}
var nowi = {
    n: "Nowi",
    vName: "nowi",
    claseBase: ["Manakete", "Wyvern Rider", "Mage"],
    sRank: ["Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Tharja", "Cherche"],
    isChilde: false,
    gender: "F",
    baseHp: 0,
    baseStr: 2,
    baseMag: 0,
    baseSkl: 1,
    baseSpd: 2,
    baseLck: 8,
    baseDef: 0,
    baseRes: 0,
    hpMod: 18,
    strMod: 4,
    magMod: 0,
    sklMod: 2,
    spdMod: 3,
    lckMod: 8,
    defMod: 2,
    resMod: 2,
    baseHpGr: 70,
    baseStrGr: 45,
    baseMagGr: 35,
    baseSklGr: 30,
    baseSpdGr: 30,
    baseLckGr: 65,
    baseDefGr: 50,
    baseResGr: 35,
}
var libra = {
    n: "Libra",
    vName: "libra",
    claseBase: ["Priest", "Mage", "Dark Mage"],
    sRank: ["Robin", "Lissa", "Sully", "Miriel", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Virion", "Gaius"],
    isChilde: false,
    gender: "M",
    baseHp: 14,
    baseStr: 9,
    baseMag: 10,
    baseSkl: 9,
    baseSpd: 7,
    baseLck: 10,
    baseDef: 5,
    baseRes: 10,
    hpMod: 38,
    strMod: 14,
    magMod: 15,
    sklMod: 13,
    spdMod: 13,
    lckMod: 10,
    defMod: 11,
    resMod: 16,
    baseHpGr: 45,
    baseStrGr: 25,
    baseMagGr: 35,
    baseSklGr: 45,
    baseSpdGr: 35,
    baseLckGr: 45,
    baseDefGr: 25,
    baseResGr: 30,
}
var tharja = {
    n: "Tharja",
    vName: "tharja",
    claseBase: ["Dark Mage", "Archer", "Knight"],
    sRank: ["Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Nowi"],
    isChilde: false,
    gender: "F",
    baseHp: 7,
    baseStr: 3,
    baseMag: 8,
    baseSkl: 3,
    baseSpd: 9,
    baseLck: 3,
    baseDef: 6,
    baseRes: 3,
    hpMod: 25,
    strMod: 4,
    magMod: 11,
    sklMod: 5,
    spdMod: 12,
    lckMod: 3,
    defMod: 10,
    resMod: 7,
    baseHpGr: 40,
    baseStrGr: 25,
    baseMagGr: 45,
    baseSklGr: 25,
    baseSpdGr: 45,
    baseLckGr: 40,
    baseDefGr: 35,
    baseResGr: 20,
}
var anna = {
    n: "Anna",
    vName: "anna",
    claseBase: ["Thief", "Archer", "Mage"],
    aRank: ["Robin", "Tiki"],
    isChilde: false,
    gender: "F",
    baseHp: 17,
    baseStr: 8,
    baseMag: 13,
    baseSkl: 12,
    baseSpd: 10,
    baseLck: 25,
    baseDef: 5,
    baseRes: 5,
    hpMod: 35,
    strMod: 12,
    magMod: 17,
    sklMod: 22,
    spdMod: 21,
    lckMod: 25,
    defMod: 8,
    resMod: 10,
    baseHpGr: 45,
    baseStrGr: 30,
    baseMagGr: 30,
    baseSklGr: 35,
    baseSpdGr: 35,
    baseLckGr: 80,
    baseDefGr: 30,
    baseResGr: 30,
}
var olivia = {
    n: "Olivia",
    vName: "olivia",
    claseBase: ["Dancer", "Myrmidion", "Pegasus Knight"],
    sRank: ["Chrom", "Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Maribelle", "Panne"],
    isChilde: false,
    gender: "F",
    baseHp: 2,
    baseStr: 2,
    baseMag: 0,
    baseSkl: 3,
    baseSpd: 1,
    baseLck: 5,
    baseDef: 0,
    baseRes: 1,
    hpMod: 18,
    strMod: 3,
    magMod: 1,
    sklMod: 8,
    spdMod: 9,
    lckMod: 5,
    defMod: 3,
    resMod: 2,
    baseHpGr: 40,
    baseStrGr: 35,
    baseMagGr: 25,
    baseSklGr: 45,
    baseSpdGr: 45,
    baseLckGr: 60,
    baseDefGr: 20,
    baseResGr: 20,
}
var cherche = {
    n: "Cherche",
    vName: "cherche",
    claseBase: ["Wyvern Rider", "Trobaudour", "cleric"],
    sRank: ["Frederick", "Virion", "Vaike", "Stahl", "Kellam", "Lon'qu", "Ricken", "Gaius", "Gregor", "Libra", "Henry"],
    aRank: ["Robin", "Miriel", "Nowi"],
    isChilde: false,
    gender: "F",
    baseHp: 12,
    baseStr: 8,
    baseMag: 1,
    baseSkl: 7,
    baseSpd: 7,
    baseLck: 9,
    baseDef: 8,
    baseRes: 2,
    hpMod: 31,
    strMod: 15,
    magMod: 1,
    sklMod: 13,
    spdMod: 12,
    lckMod: 9,
    defMod: 16,
    resMod: 2,
    baseHpGr: 55,
    baseStrGr: 40,
    baseMagGr: 20,
    baseSklGr: 40,
    baseSpdGr: 35,
    baseLckGr: 50,
    baseDefGr: 45,
    baseResGr: 10,
}
var henry = {
    n: "Henry",
    vName: "henry",
    claseBase: ["Dark Mage", "Barbarian", "Thief"],
    sRank: ["Robin", "Lissa", "Sully", "Miriel", "Sumia", "Maribelle", "Panne", "Cordelia", "Nowi", "Tharja", "Olivia", "Cherche"],
    aRank: ["Frederick", "Ricken"],
    isChilde: false,
    gender: "M",
    baseHp: 11,
    baseStr: 5,
    baseMag: 11,
    baseSkl: 13,
    baseSpd: 6,
    baseLck: 10,
    baseDef: 9,
    baseRes: 1,
    hpMod: 29,
    strMod: 6,
    magMod: 14,
    sklMod: 15,
    spdMod: 9,
    lckMod: 10,
    defMod: 13,
    resMod: 5,
    baseHpGr: 45,
    baseStrGr: 35,
    baseMagGr: 35,
    baseSklGr: 45,
    baseSpdGr: 40,
    baseLckGr: 40,
    baseDefGr: 40,
    baseResGr: 20,
}

var noUnit = {
    n: "-",
    vName: "-",
    claseBase: ["-"],
    sRank: [],
    aRank: [],
    isChilde: false,
    gender: "N",
    baseHp: 0,
    baseStr: 0,
    baseMag: 0,
    baseSkl: 0,
    baseSpd: 0,
    baseLck: 0,
    baseDef: 0,
    baseRes: 0,
    hpMod: 0,
    strMod: 0,
    magMod: 0,
    sklMod: 0,
    spdMod: 0,
    lckMod: 0,
    defMod: 0,
    resMod: 0,
    baseHpGr: 0,
    baseStrGr: 0,
    baseMagGr: 0,
    baseSklGr: 0,
    baseSpdGr: 0,
    baseLckGr: 0,
    baseDefGr: 0,
    baseResGr: 0,
}


//arrays de unidades
var allUnits = [robin, chrom, lissa, frederick, sully, virion, stahl, vaike, miriel, sumia, kellam, lonqu, donnel, ricken, maribelle, panne, gaius, cordelia, gregor, nowi, anna, libra, tharja, olivia, cherche, henry]

//hacer array de los stats
function statBaseArray(unit){
    return[unit.baseHp, unit.baseStr, unit.baseMag, unit.baseSkl, unit.baseSpd, unit.baseLck, unit.baseDef, unit.baseRes]
}
function statModsArray(unit){
    return[unit.hpMod, unit.strMod, unit.magMod, unit.sklMod, unit.spdMod, unit.lckMod, unit.defMod, unit.resMod]
}

function growthBaseArray(unit){
    return [unit.baseHpGr, unit.baseStrGr, unit.baseMagGr, unit.baseSklGr, unit.baseSpdGr, unit.baseLckGr, unit.baseDefGr, unit.baseDefGr]
}
function growthModsArray(unit){
    return [unit.hpGr, unit.strGr, unit.magGr, unit.sklGr, unit.spdGr, unit.lckGr, unit.defGr, unit.resGr]
}